#!/bin/bash

is_ready() {
    eval [ $(curl --write-out %{http_code} --silent --output /dev/null http://elastic-dataops:9200/_cat/health?h=st) = 200 ]
}

# wait until is ready
i=0
while ! is_ready; do
    i=`expr $i + 1`
    if [ $i -ge 30 ]; then
        echo "$(date) - still not ready, giving up"
        exit 1
    fi
    echo "$(date) - waiting to be ready"
    sleep 2
done


curl -H 'Content-Type: application/json' -XPOST http://elastic-dataops:9200/_bulk --data-binary @/data/movies-db-bulk.json
